# Generated by Django 4.0.4 on 2022-08-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_helper', '0002_alter_follower_options_alter_loverecipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_about',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_gender',
            new_name='gender',
        ),
    ]
