# Generated by Django 4.0.4 on 2022-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_helper', '0003_rename_user_about_profile_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_url', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Отметка нравится',
                'verbose_name_plural': 'Отметки нравится',
            },
        ),
        migrations.RenameModel(
            old_name='LoveRecipe',
            new_name='FavouriteRecipe',
        ),
        migrations.AlterModelOptions(
            name='favouriterecipe',
            options={'verbose_name': 'Отметка любимый', 'verbose_name_plural': 'Отметки любимый'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='lovers',
            new_name='favourite',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
