# Generated by Django 4.0.4 on 2022-08-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_helper', '0004_likerecipe_rename_loverecipe_favouriterecipe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteRecipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favourite',
        ),
    ]
