# Generated by Django 4.0.4 on 2022-08-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_helper', '0005_delete_favouriterecipe_remove_recipe_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecipe',
            old_name='recipe_url',
            new_name='recipe_id',
        ),
    ]
